#!/bin/bash

# SBT configuration
export SBT_BOOT_DIR=${HOME}/.sbt/boot/

if [ ! -d "${SBT_BOOT_DIR}" ]; then
  mkdir -p ${SBT_BOOT_DIR}
fi

if [ -f "~/.sbtconfig" ]; then
  . ~/.sbtconfig
fi

java -Xmx768M -XX:MaxPermSize=384m \
        $SBT_EXTRA_PARAMS \
        -jar `dirname $0`/dev/sbt-launch-0.11.2.jar "$@"
